export const dawn = [
    {
        name: "Penguin Dance",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_1.jpg",
        overlay: "../img/overlay/dawn_1.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 200cm",
        ratio: 1.43,
        format: "w",
        index: 0,
    },
    {
        name: "Just arrived",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_2.jpg",
        overlay: "../img/overlay/dawn_2.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 180cm",
        ratio: 1.5,
        format: "w",
        index: 1,
    },
    {
        name: "Birdwalk",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_3.jpg",
        overlay: "../img/overlay/dawn_3.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 230cm",
        ratio: 1.5,
        format: "w",
        index: 2,
    },
    {
        name: " Blue Birds Crossing",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_4.jpg",
        overlay: "../img/overlay/dawn_4.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 220cm",
        ratio: 1.5,
        format: "w",
        index: 3,
    },
    {
        name: "Touch",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_5.jpg",
        overlay: "../img/overlay/dawn_5.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 120cm",
        ratio: 0.8,
        format: "h",
        index: 4,
    },
    {
        name: "On the beach",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_6.jpg",
        overlay: "../img/overlay/dawn_6.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 100cm",
        ratio: 1,
        format: "q",
        index: 5,
    },
    {
        name: "Paperplane Pilots",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_7.jpg",
        overlay: "../img/overlay/dawn_7.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 150cm",
        ratio: 1.34,
        format: "w",
        index: 6,
    },
    {
        name: "Sleeping Ferryman",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_8.jpg",
        overlay: "../img/overlay/dawn_8.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        ratio: 1.32,
        format: "w",
        index: 7,
    },
    {
        name: "Gods in Love",
        kategorie: "Dawn",
        link: "../img/bilder/dawn_9.jpg",
        overlay: "../img/overlay/dawn_9.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        ratio: 1.2,
        format: "w",
        index: 8,
    },
];

export const magnificent = [
    {
        name: "Magificent",
        kategorie: "Magnificent",
        link: "../img/bilder/magnificent_1.jpg",
        overlay: "../img/overlay/magnificent_1.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 100cm",
        ratio: 1,
        format: "q",
        index: 0,
    },
    {
        name: "Magificent",
        kategorie: "Magnificent",
        link: "../img/bilder/magnificent_2.jpg",
        overlay: "../img/overlay/magnificent_2.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        ratio: 1,
        format: "q",
        index: 1,
    },
    {
        name: "Magificent",
        kategorie: "Magnificent",
        link: "../img/bilder/magnificent_3.jpg",
        overlay: "../img/overlay/magnificent_3.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        ratio: 1,
        format: "q",
        index: 2,
    },
    {
        name: "Magificent",
        kategorie: "Magnificent",
        link: "../img/bilder/magnificent_4.jpg",
        overlay: "../img/overlay/magnificent_4.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        ratio: 1,
        format: "q",
        index: 3,
    },
];

export const garden = [
    {
        name: "Blue Poppie",
        kategorie: "Garden",
        link: "../img/bilder/garden_1.jpg",
        overlay: "../img/overlay/garden_1.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        index: 0,
    },
    {
        name: "Rose",
        kategorie: "Garden",
        link: "../img/bilder/garden_2.jpg",
        overlay: "../img/overlay/garden_2.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        index: 1,
    },
    {
        name: "Harlekin",
        kategorie: "Garden",
        link: "../img/bilder/garden_3.jpg",
        overlay: "../img/overlay/garden_3.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 120cm",
        index: 2,
    },
    {
        name: "What's up",
        kategorie: "Garden",
        link: "../img/bilder/garden_4.jpg",
        overlay: "../img/overlay/garden_4.jpg",
        stil: "Acryl auf Leinwand",
        size: "90cm x 90cm",
        index: 3,
    },
];

export const heat = [
    {
        name: "Dance",
        kategorie: "Heat",
        link: "../img/bilder/heat_1.jpg",
        overlay: "../img/overlay/heat_1.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 150cm",
        index: 0,
    },
    {
        name: "In the Jungle",
        kategorie: "Heat",
        link: "../img/bilder/heat_2.jpg",
        overlay: "../img/overlay/heat_2.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 180cm",
        index: 1,
    },
    {
        name: "Waiting",
        kategorie: "Heat",
        link: "../img/bilder/heat_3.jpg",
        overlay: "../img/overlay/heat_3.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 180cm",
        index: 2,
    },
    {
        name: "Veins",
        kategorie: "Heat",
        link: "../img/bilder/heat_4.jpg",
        overlay: "../img/overlay/heat_4.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 180cm",
        index: 3,
    },
];

export const nature = [
    {
        name: "Trees",
        kategorie: "Nature",
        link: "../img/bilder/nature_1.jpg",
        overlay: "../img/overlay/nature_1.jpg",
        stil: "Pigment & Bienenwachs",
        size: "100cm x 100cm",
        index: 0,
    },
    {
        name: "Trees",
        kategorie: "Nature",
        link: "../img/bilder/nature_2.jpg",
        overlay: "../img/overlay/nature_2.jpg",
        stil: "Pigment & Bienenwachs",
        size: "100cm x 100cm",
        index: 1,
    },
    {
        name: "Landscape",
        kategorie: "Nature",
        link: "../img/bilder/nature_3.jpg",
        overlay: "../img/overlay/nature_3.jpg",
        stil: "Pigment & Bienenwachs",
        size: "100cm x 100cm",
        index: 2,
    },
    {
        name: "Venice",
        kategorie: "Nature",
        link: "../img/bilder/nature_4.jpg",
        overlay: "../img/overlay/nature_4.jpg",
        stil: "Pigment & Bienenwachs",
        size: "80cm x 120cm",
        index: 3,
    },
    {
        name: "Trees",
        kategorie: "Nature",
        link: "../img/bilder/nature_5.jpg",
        overlay: "../img/overlay/nature_5.jpg",
        stil: "Pigment & Bienenwachs",
        size: "100cm x 100cm",
        index: 4,
    },
    {
        name: "River Meadows",
        kategorie: "Nature",
        link: "../img/bilder/nature_6.jpg",
        overlay: "../img/overlay/nature_6.jpg",
        stil: "Pigment & Bienenwachs",
        size: "50cm x 50cm",
        index: 5,
    },
    {
        name: "Trees",
        kategorie: "Nature",
        link: "../img/bilder/nature_7.jpg",
        overlay: "../img/overlay/nature_7.jpg",
        stil: "Pigment & Bienenwachs",
        size: "100cm x 100cm",
        index: 6,
    },
    {
        name: "River Meadows",
        kategorie: "Nature",
        link: "../img/bilder/nature_8.jpg",
        overlay: "../img/overlay/nature_8.jpg",
        stil: "Pigment & Bienenwachs",
        size: "50cm x 50cm",
        index: 7,
    },
    {
        name: "Venice",
        kategorie: "Nature",
        link: "../img/bilder/nature_9.jpg",
        overlay: "../img/overlay/nature_9.jpg",
        stil: "Acryl auf Leinwand",
        size: "80cm x 100cm",
        index: 8,
    },
    {
        name: "Venice",
        kategorie: "Nature",
        link: "../img/bilder/nature_10.jpg",
        overlay: "../img/overlay/nature_10.jpg",
        stil: "Pigment & Bienenwachs",
        size: "80cm x 100cm",
        index: 9,
    },
    {
        name: "Venice",
        kategorie: "Nature",
        link: "../img/bilder/nature_11.jpg",
        overlay: "../img/overlay/nature_11.jpg",
        stil: "Pigment & Bienenwachs",
        size: "80cm x 100cm",
        index: 10,
    },
    {
        name: "Mountains",
        kategorie: "Nature",
        link: "../img/bilder/nature_12.jpg",
        overlay: "../img/overlay/nature_12.jpg",
        stil: "Pigment & Bienenwachs",
        size: "40cm x 40cm",
        index: 11,
    },
];

export const layers = [
    {
        name: "Faces",
        kategorie: "Layers",
        link: "../img/bilder/layers_1.jpg",
        overlay: "../img/overlay/layers_1.jpg",
        stil: "Acryl & Kohle",
        size: "110cm x 150cm",
        index: 0,
    },
    {
        name: "Dance",
        kategorie: "Layers",
        link: "../img/bilder/layers_2.jpg",
        overlay: "../img/overlay/layers_2.jpg",
        stil: "Acryl & Kohle",
        size: "110cm x 150cm",
        index: 1,
    },
    {
        name: "Baloon",
        kategorie: "Layers",
        link: "../img/bilder/layers_3.jpg",
        overlay: "../img/overlay/layers_3.jpg",
        stil: "Acryl & Kohle",
        size: "110cm x 130cm",
        index: 2,
    },
    {
        name: "Visions",
        kategorie: "Layers",
        link: "../img/bilder/layers_4.jpg",
        overlay: "../img/overlay/layers_4.jpg",
        stil: "Acryl & Kohle",
        size: "110cm x 120cm",
        index: 3,
    },
    {
        name: "Dreaming Plants",
        kategorie: "Layers",
        link: "../img/bilder/layers_5.jpg",
        overlay: "../img/overlay/layers_5.jpg",
        stil: "Acryl & Kohle",
        size: "110cm x 120cm",
        index: 4,
    },
    {
        name: "History",
        kategorie: "Layers",
        link: "../img/bilder/layers_6.jpg",
        overlay: "../img/overlay/layers_6.jpg",
        stil: "Acryl & Kohle",
        size: "110cm x 240cm",
        index: 5,
    },
];
export const rainyspring = [
    {
        name: "Nat & Gonba",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_1.jpg",
        overlay: "../img/overlay/rainyspring_1.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 180cm",
        index: 0,
    },
    {
        name: "Rainy Spring",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_2.jpg",
        overlay: "../img/overlay/rainyspring_2.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 180cm",
        index: 1,
    },
    {
        name: "Malach",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_3.jpg",
        overlay: "../img/overlay/rainyspring_3.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 180cm",
        index: 2,
    },
    {
        name: "Sanktum",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_4.jpg",
        overlay: "../img/overlay/rainyspring_4.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 180cm",
        index: 3,
    },
    {
        name: "Der Baum",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_5.jpg",
        overlay: "../img/overlay/rainyspring_5.jpg",
        stil: "Acryl auf Leinwand",
        size: "150cm x 180cm",
        index: 4,
    },
    {
        name: "Nala",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_6.jpg",
        overlay: "../img/overlay/rainyspring_6.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 180cm",
        index: 5,
    },
    {
        name: "Die Wüste",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_7.jpg",
        overlay: "../img/overlay/rainyspring_7.jpg",
        stil: "Acryl auf Leinwand",
        size: "130cm x 180cm",
        index: 6,
    },
    {
        name: "Bardocks",
        kategorie: "Rainy Spring",
        link: "../img/bilder/rainyspring_8.jpg",
        overlay: "../img/overlay/rainyspring_8.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 180cm",
        index: 7,
    },
];
export const winter = [
    {
        name: "The Art of Storytelling",
        kategorie: "Winter",
        link: "../img/bilder/winter_1.jpg",
        overlay: "../img/overlay/winter_1.jpg",
        stil: "Acryl & Kohle",
        size: "150cm x 180cm",
        index: 0,
    },
    {
        name: "Frau Holle spielt mit der Welt",
        kategorie: "Winter",
        link: "../img/bilder/winter_2.jpg",
        overlay: "../img/overlay/winter_2.jpg",
        stil: "Acryl & Kohle",
        size: "150cm x 180cm",
        index: 1,
    },
    {
        name: "Reset",
        kategorie: "Winter",
        link: "../img/bilder/winter_3.jpg",
        overlay: "../img/overlay/winter_3.jpg",
        stil: "Acryl auf Leinwand",
        size: "120cm x 150cm",
        index: 2,
    },
    {
        name: "Doing Philosophy with Ravens",
        kategorie: "Winter",
        link: "../img/bilder/winter_2.jpg",
        overlay: "../img/overlay/winter_2.jpg",
        stil: "Acryl & Kohle",
        size: "150cm x 180cm",
        index: 3,
    },
];

export const flood = [
    {
        name: "Rivernight Stories",
        kategorie: "Winter",
        link: "../img/bilder/flood_1.jpg",
        overlay: "../img/overlay/flood_1.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 100cm",
        index: 0,
    },
    {
        name: "Rivernight Stories",
        kategorie: "Winter",
        link: "../img/bilder/flood_2.jpg",
        overlay: "../img/overlay/flood_2.jpg",
        stil: "Acryl auf Leinwand",
        size: "100cm x 100cm",
        index: 1,
    },
];
